name: homepage
description: "A place to call home in the vast ocean of the internet"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http:
  shimmer:
  intl:
  url_launcher:
  supabase_flutter:
  font_awesome_flutter: ^10.8.0
  provider:
  flutter_confetti:
  msh_checkbox:
  flutter_spinkit:
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/pine_trees.jpg

